# Generated by Django 4.0.2 on 2022-02-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_learn_published_date_learn_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learncontent',
            name='full_content',
        ),
        migrations.AddField(
            model_name='learncontent',
            name='content_type',
            field=models.CharField(choices=[('BOT', 'Both'), ('FUL', 'Full'), ('IMG', 'Image')], default='BOT', max_length=3),
        ),
        migrations.AddField(
            model_name='learncontent',
            name='full_image',
            field=models.ImageField(default='default.jpg', upload_to='contentImages'),
        ),
        migrations.AddField(
            model_name='learncontent',
            name='show_preview',
            field=models.BooleanField(default=False),
        ),
    ]
