# Generated by Django 4.0.2 on 2022-02-28 01:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(default='default-project.jpg', upload_to='projectContentImages')),
                ('content_position', models.CharField(choices=[('LFT', 'Left'), ('RHT', 'Right'), ('FUL', 'Full'), ('IMG', 'Image')], default='LFT', max_length=3)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
        ),
    ]
