# Generated by Django 4.0.2 on 2022-02-28 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_project_is_external_projectcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='Enter project url', max_length=300),
        ),
    ]
