# Generated by Django 4.0.2 on 2022-02-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_project_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview',
            field=models.ImageField(default='default.jpg', upload_to='projectImages'),
        ),
    ]
