# Generated by Django 4.0.2 on 2022-03-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_project_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='no_image',
            field=models.BooleanField(default=False, help_text='No Image'),
        ),
    ]
