# Generated by Django 4.0.2 on 2022-03-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_article_no_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='articleImages'),
        ),
    ]
