# Generated by Django 4.0.2 on 2022-03-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='articleImages'),
        ),
    ]
