# Generated by Django 4.0.2 on 2022-03-02 05:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learncontent',
            name='code',
            field=tinymce.models.HTMLField(help_text='Enter in the code'),
        ),
        migrations.AlterField(
            model_name='learncontent',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
