# Generated by Django 4.0.2 on 2022-03-02 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_learncontent_code_alter_learncontent_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
                ('link', models.URLField(blank=True, max_length=300)),
                ('about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.about')),
            ],
        ),
    ]
