# Generated by Django 4.0.2 on 2022-03-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_abouttimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttimeline',
            name='summary',
            field=models.CharField(max_length=1000),
        ),
    ]
