"""
Django settings for kproject project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(%ox1)+tge!a34e9628r3=-yfk(8mb)k-!)#9iy%fnwd1)3(!('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website.apps.WebsiteConfig',
    'tinymce',
]

TINYMCE_DEFAULT_CONFIG = {
    "height": "500px",
    "width": "960px",
    'cleanup_on_startup': True,
    'selector': 'textarea',
    "menubar": "file edit view insert format tools table help",
    'plugins': '''
                print preview paste importcss searchreplace autolink 
                autosave save directionality code visualblocks visualchars 
                fullscreen image link media template codesample table charmap 
                hr pagebreak nonbreaking anchor toc insertdatetime advlist 
                lists wordcount imagetools textpattern noneditable help charmap
                quickbars emoticons spellchecker
                ''',
    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft "
               "aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor "
               "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "
               "fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | "
               "a11ycheck ltr rtl | showcomments addcomment code",
    "custom_undo_redo_levels": 10,
    "templates": [
        {
            "title": "Tip Box",
            "description": "Inline tip box",
            "content": """
                <div class='tip-box'>
                    <div class='tip-box-content'>
                        <div class='tip-box-content-title'>Tip</div>
                        <div class='tip-box-content-tip'>content</div>
                    </div>
                </div>
            """
        },
        {
            "title": "Caution Box",
            "description": "Inline caution box",
            "content": """
                <div class='caution-box'>
                    <div class='caution-box-content'>
                        <div class='caution-box-content-title'>Caution</div>
                        <div class='caution-box-content-tip'>Caution content</div>
                    </div>
                </div>
            """
        },
        {
            "title": "Content Box",
            "description": "Inline content box",
            "content": """
                <div class='info-box'>
                    <div class='info-box-content'>content</div>
                    <div class='info-box-caption'>caption</div>
                </div>
            """
        },
        {
            "title": "Quote Box",
            "description": "Quote Box",
            "content": """
                 <div class='quote-box'>
                    <div class='quote-box-content'>
                        <div>quote</div>
                        <div class='quote-box-content-title'>author</div>
                    </div>
                </div>
            """
        },
        {
            "title": "Link Image Box",
            "description": "Inline image box",
            "content": """
                <div class='img-box'>
                    link
                </div>
            """
        }
    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kprodb',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Canada/Central'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, "/static/")

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
